### ISSUE TITLE
zvětšení nečitelných obrázků/doplnění odkazu

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/skoleni-test#10]
**Kurz publikační plán, modul-08/#/11/0/0:** obrázek diagramu k podmínkám užití je nečitelný, doporučuji ho zvětšit a doplnit odkaz do [opendata webu](https://opendata.gov.cz/cinnost:stanoveni-podminek-uziti?s[]=diagram#rozhodovac%C3%AD_diagram_pro_stanoven%C3%AD_podm%C3%ADnek_u%C5%BEit%C3%AD_a_licencov%C3%A1n%C3%AD_chr%C3%A1n%C4%9Bn%C3%A9ho_obsahu)

**Obecně:** velmi malé obrázky jsou i v jiných modulech a obsah není čitelný, na slajdech je hodně nevyužitého prostoru, takže doporučuji zvětšit tam kde to jde

**Comment by martinvita** [comment]
Obrázek diagramu zvětšen, odkaz doplněn.
Co se týká obrázků - MaNe to také zmiňoval, udělal jsem to podle #opendataskoleni.
Font na slidech, kde je hodně nevyužitého prostoru ale zvětšovat nebudeme, nedělalo by to dobrotu, jak jsme se bavili s JaKl a MaNe na #opendataskoleni.

**Comment by skodapetr** [comment]
Některé obrázky mají malé rozlišení na to, aby bylo možné je dostatečně zvětšit - otázka je, jak moc je chcem zvětšovat, příklad 
https://opendata-mvcr.github.io/skoleni-test/modul-04/index.html#/7 , obrázek má velikost kolem 800x300.
