### ISSUE TITLE
Obrázky v temném módu

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/skoleni-test#11]
V prezentaci jsou obrázky na bílém pozadí, například ilustrace dialogů - toto je poněkud rušivé v temném módu. Bylo by možné využít formátu jenž umožňuje pracovat s barvou, nebo mít více verzí? Tak aby pozadí bylo bílé/černé dle preferovaného módu zobrazení? Příklad https://opendata-mvcr.github.io/skoleni-test/modul-01/index.html#/5

**Comment by skodapetr** [comment]
V https://opendata-mvcr.github.io/skoleni-test/modul-u04/index.html#/17/0/1 je obrázek s průhledným pozadím, v temném módu není černý text čitelný.

**Comment by jakubklimek** [comment]
Domluva byla, že obrázky budou mít bílé pozadí.
Mít více verzí je problematické, jelikož by se správná verze musela nastavovat v CSS (nějaký background-image nebo tak něco) a ne v HTML, které o preferovaném režimu neví.

Ideální to není, ale je to použitelné. Zlepšovat můžeme později - dělá se to např. nastavením průhlednosti v tmavém režimu pro snížení kontrastu.
