### ISSUE TITLE
Odkaz obrázkem

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/skoleni-test#12]
V https://opendata-mvcr.github.io/skoleni-test/modul-05/index.html#/6/0/1 je odkaz pomocí obrázku. Nebylo by lepší dát odkaz jako text nad obrázkem a obrázek nechat bez akce? Text nad obrázkem je "Prohlédněte si je!"

**Comment by jakubklimek** [comment]
Určitě ano
