### ISSUE TITLE
Odkaz na opendata.gov.cz

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/skoleni-test#15]
Některé odkazy obsahují specifikaci pro vyhledávání napříkla: 
https://opendata.gov.cz/cinnost:stanoveni-podminek-uziti?s%5B%5D=diagram#rozhodovac%C3%AD_diagram_pro_stanoven%C3%AD_podm%C3%ADnek_u%C5%BEit%C3%AD_a_licencov%C3%A1n%C3%AD_chr%C3%A1n%C4%9Bn%C3%A9ho_obsahu

z https://opendata-mvcr.github.io/skoleni-test/modul-08/index.html#/11/0/0
to pak vede ke zvýraznění pojmu zde "diagram"  na zobrazené strán.ce

**Comment by jakubklimek** [comment]
Ano, to je špatně.
