### ISSUE TITLE
Definice šablon

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/skoleni-test#4]
Bylo by přínosné, pokud bychom mohli definovat a používat šablony pro slajdy. Například 

![image](https://user-images.githubusercontent.com/3341693/121708485-e729fc80-cad7-11eb-9eac-f8cb37efc078.png)

by mohl být slajd s obrázkem, kde obrázek je centrován s zvětšen/zmenšen aby zabral pokud možno celý slajd.

**Comment by jakubklimek** [comment]
Opět řešitelné jekyllem, viz posty na data.gov.cz a include obrázků.

**Comment by skodapetr** [comment]
Nechápu tu spojitost a proč by sem měl Jekyl vstupovat, šlo by to nějak rozepsat ?

**Comment by jakubklimek** [comment]
No ze muzes poresit ty sablony. Napr pres layouts a nebo ze pripravis, jako na data.gov.cz, aspon include obrazku, ktery zaridi ze bude spravne centrovany, s popiskem atd.
