### ISSUE TITLE
Uvážit možnost vypnutí fragmentů

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/skoleni-test#7]
Ve slajdech se aktuálně hojně využívá fragmentů, tedy postupné zobrazní prvků, zejména textu. Nicméně to poněkud zpomaluje rychlejší prohlížení. Možná by bylo zajímvé prozkoumat možnost, jak fragmenty "deaktivovat" a vidět tak vždy rovnou plný slide.

**Comment by jakubklimek** [comment]
+1. Taky si nejsem jistý že je třeba rozanimovávat jednotlivé body.

**Comment by skodapetr** [comment]
To záleží zda-li je o materiál pro internet, tam smysl nevidím. Pokud bych to ale měl použít pro prezetnaci, tak si umím představit, že si každý může chtít ty dynamiku slajdů přizpůsobit svému stylu.

**Comment by jakubklimek** [comment]
Je to pro Internet.
