### ISSUE TITLE
Použití jekyll pro šablony

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/skoleni-test#8]
Aktuálně má každý modul část s obsahem. Dále pak mají všechny moduly stejnou hlavičku a patičku. Z hlediska údržby by byo snazší, využít Jeykku a jeho šablon tak, aby byla hlavička a patička specifikována pouze v jenom souboru. 

Nevýhodou je nemožnost prezentace přímo otevřít jako "samostatné" HTML soubory.

**Comment by jakubklimek** [comment]
To nevidim jako nevýhodu. Neuvidíš to ostylovaný, ale text ano. Zapnout jekyll pak není problém, případně zprovoznit github pages.

**Comment by skodapetr** [comment]
No nebude to validní HTML a ten text nemusí pak moc dávat smysl .. a zapnout Jekyll může/je být problém pro lokální vývoj. Tam bych čekal spíše s tím, že si člověk hodl vezme ten layout a bude pracovat s ním, až bude hotovo tak ho smaže.

**Comment by jakubklimek** [comment]
Nepise se to v Markdownu?

**Comment by skodapetr** [comment]
Je to volitelné, funguje t tak, že se část MD vloží do HTML na místo slajdu. Nicméně aktuálně je vše co máme v HTML.
